spring:
  application:
    name: service-verification-code
  redis:
    host: 81.70.**.***
    port: 6379
    password: ALLFOOBAR

server:
  port: 19000

eureka:
  client:
    service-url:
      #      defaultZone: http://alongso:123456@localhost:7900/eureka/
      defaultZone: http://localhost:7900/eureka/


