server:
  port: 9001

spring:
  application:
    name: consumer


eureka:
  client:
    service-url:
      defaultZone: http://alongso:123456@localhost:7900/eureka/
    # 将自己真正的健康状态传播到server。
    healthcheck:
      enabled: true

# 暴露所有接口，默认只暴露health接口
management:
  endpoints:
    web:
      exposure:
        include: '*'
  # http://127.0.0.1:9001//actuator/shutdown 可手动停调服务
  endpoint:
    shutdown:
      enabled: true

# 针对某个服务指定
#api-passenger:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#  listOfServers: localhost:8001
#  eureka:
#    enabled: false
  ConnectTimeout: 1000
  ReadTimeout: 2000
  #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetries: 0
  #重试负载均衡其他的实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 0
  #是否所有操作都重试
  OkToRetryOnAllOperations: false

feign:
  hystrix:
    enabled: true