server:
  port: 8000
spring:
  application:
    name: api-passenger
  #zipkin
  zipkin:
    base-url: http://127.0.0.1:9411/
    sender: web
  #采样比例1
  sleuth:
    sampler:
      rate: 1
  boot:
    admin:
      client:
        url: http://127.0.0.1:8888
  redis:
    host: 81.70.**.***
    port: 6379
    password: ALLFOOBAR

eureka:
  client:
    service-url:
#      defaultZone: http://alongso:123456@localhost:7900/eureka/
      defaultZone: http://localhost:7900/eureka/

# 暴露所有接口，默认只暴露health接口
management:
  endpoints:
    web:
      exposure:
        include: '*'
  # http://127.0.0.1:9001//actuator/shutdown 可手动停调服务
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always


# 集群部署
---
spring:
  profiles: 8001
server:
  port: 8001
sleep:
  time: 1

---
spring:
  profiles: 8002
server:
  port: 8002
sleep:
  time: 3

